name: organizador_de_email
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  loading_animation_widget: ^1.2.0+1
  like_button: ^2.0.4
  flutter_native_splash: ^2.2.1
  http: ^0.13.4
  anim_search_bar: ^2.0.2
  flutter_slidable: ^1.3.0
  process_run: ^0.12.3+2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter_native_splash:

  android: true
  ios: false
  web: false

  color: "#00C2CB"
  image: images/logo.png

flutter:

  uses-material-design: true

  assets:
    - images/henrique.jpeg
    - images/logo.png
    - json/email1.json
